version: "3.5"

services:
    backend-test:
        build:
            dockerfile: backend/docker/Dockerfile
            context: .
        environment:
            - DB_USER=weathertalk
            - DB_PASSWORD=weathertalkdatabasepasswordplzchange
            - DB_HOST=postgres-test
        ports:
            - 5000:5000
        links:
            - postgres-test
        networks:
            - internal
        command: ["postgres-test", "testing"]

    postgres-test:
        image: postgres:12.2-alpine
        environment:
            POSTGRES_PASSWORD: weathertalkdatabasepasswordplzchange
            POSTGRES_USER: weathertalk
            POSTGRES_DB: weathertalk

        networks:
            - internal

networks:
    internal:
        driver: bridge