version: "3.5"

services:
    backend:
        build:
            dockerfile: backend/docker/Dockerfile
            context: .
        environment:
            - DB_USER=weathertalk
            - DB_PASSWORD=weathertalkdatabasepasswordplzchange
            - DB_HOST=postgres
        ports:
            - 5000:5000
        links:
            - postgres
        networks:
            - internal
        command: ["postgres"]

    nginx:
        image: nginx:1.17.6
        ports:
            - "80:80"
        links:
            - backend
            - postgres
        volumes:
            - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf
        networks:
            - internal

    postgres:
        image: postgres:12.2-alpine
        environment:
            POSTGRES_PASSWORD: weathertalkdatabasepasswordplzchange
            POSTGRES_USER: weathertalk
            POSTGRES_DB: weathertalk

        networks:
            - internal

networks:
    internal:
        driver: bridge