version: "3.5"

services:
    backend:
        build:
            dockerfile: backend/docker/Dockerfile
            context: .
        environment:
            - DB_USER=""
            - DB_PASSWORD=""
        ports:
            - 5000:5000
        networks:
            - internal
        command: ["gunicorn", "--workers", "5", "wsgi:app", "--bind", "0.0.0.0:5000"]

    nginx:
        image: nginx:1.17.6
        ports:
            - "80:80"
        links:
            - backend
        volumes:
            - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf
        networks:
            - internal

networks:
    internal:
        driver: bridge